version: '2'
services:
  client:
    container_name: 'client'
    build: client
    ports:
      - '4200:4200'
      - '49152:49152'
      - '9876:9876'
    volumes:
      - './client:/home/app/client'
    env_file: .env
    command: npm start
  server:
    container_name: 'server'
    build: server
    ports:
      - '3000:3000'
    volumes:
      - './server/routes:/home/app/server/routes'
    depends_on:
      - postgres
    env_file: .env
    command: npm start
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=demo
      - POSTGRES_PASSWORD=qwerty1234
    image: 'postgres:latest'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - './util/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh'
